Services - Home Services:
  summary: Booking Home Services
  description: >-
    This elaborates the model implementations for booking home services over the network.
    The booking majorly happens in four phases of order processing flow, i.e. Discovery of available services and service providers based on serviceability, order, fulfillment and post-fulfillment.
  example_set:
    $ref: "./Services_home_service_yaml/index.yaml"
Services - Requote Services:
  summary: Booking Services which require inspection
  description: >-
    This elaborates the model implementations for booking home services over the network, which initially requires inspection.
    The booking majorly happens in four phases of order processing flow, i.e. Discovery of available services and service providers based on serviceability, order, inspection, requotation phase.
  example_set:
    $ref: "./Services_home_service_yaml/index.yaml"